# -*- coding: utf-8 -*-
"""Try 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ebJaDaxEaA_wbSKtOFJoAJx7cF16Jli0
"""

import numpy
import pandas as pd
from google.colab import files
data_to_load = files.upload()
import io
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression

dtf = pd.read_csv(io.BytesIO(data_to_load['train.csv']))
dtf

model = LogisticRegression()
dtf['male'] = dtf['Sex'] == 'male'
moy = sum(dtf['Fare'])/len(dtf['Fare'])
moy2 = sum(dtf['Age'])/len(dtf['Age'])
dtf['Fare'] = dtf['Fare'].fillna(moy)
dtf['Age'] = dtf['Age'].fillna(moy2)
dfx = dtf[['Age','Pclass','male','Fare','SibSp','Parch']]
dfx

X = dfx.values
y = dtf['Survived'].values
model.fit(X,y)
print(model.coef_)
print(model.score(X,y))
print(model.predict(X[:5]))
print(model.predict([[29,1,True,7,0,2]]))





plt.scatter(dtf['Age'], dtf['Fare'], c=dtf['Pclass'])
plt.plot([0, 80], [85, 5])